# Lectura de Fuentes

## Anexo 1: registro de muertes

In [ ]:
import pandas as pd

data_anex_1 = pd.read_excel("data/anexo_1.xlsx")
data_anex_1

,COD_DANE,COD_DEPARTAMENTO,COD_MUNICIPIO,AREA_DEFUNCION,SITIO_DEFUNCION,AÑO,MES,HORA,MINUTOS,SEXO,ESTADO_CIVIL,GRUPO_EDAD1,NIVEL_EDUCATIVO,MANERA_MUERTE,COD_MUERTE,IDPROFESIONAL
0,66682,66,682,1,5,2019,11,23,0,2,5.0,15,3,Homicidio,X994,1
1,17001,17,1,1,1,2019,12,21,10,1,6.0,16,2,Natural,C712,1
2,25843,25,843,1,1,2019,12,20,15,2,4.0,19,2,Sin Determinar,Y349,1
3,23001,23,1,1,1,2019,12,14,20,2,1.0,23,2,Natural,I678,1
4,73001,73,1,1,1,2019,11,8,40,2,4.0,23,2,Natural,F03,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,11,1,1,1,2019,5,0,0,1,5.0,13,3,Homicidio,X954,1
244351,97161,97,161,3,3,2019,9,4,30,1,1.0,17,2,Accidente,W330,3
244352,76001,76,1,1,5,2019,9,0,0,1,9.0,14,2,Homicidio,X954,1
244353,76109,76,109,1,1,2019,7,14,15,1,5.0,11,4,Accidente,W858,1
244354,76109,76,109,1,5,2019,2,0,0,1,1.0,11,2,Accidente,V892,1

In [19]:
len(data_anex_1)

244355

## Anexo 2: diccionario de muertes

In [2]:
data_anex_2 = pd.read_excel("data/anexo_2.xlsx", header = 8)
data_anex_2

,Capítulo,Nombre capítulo,Código de la CIE-10 tres caracteres,Descripción de códigos mortalidad a tres caracteres,Código de la CIE-10 cuatro caracteres,Descripcion de códigos mortalidad a cuatro caracteres
0,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A000,"Colera debido a Vibrio cholerae 01, biotipo ch..."
1,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A001,"Colera debido a Vibrio cholerae 01, biotipo el..."
2,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A009,"Colera, no especificado"
3,1,Ciertas enfermedades infecciosas y parasitaria...,A01,Fiebres Tifoidea Y Paratifoidea,A010,Fiebre tifoidea
4,1,Ciertas enfermedades infecciosas y parasitaria...,A01,Fiebres Tifoidea Y Paratifoidea,A011,Fiebre paratifoidea A
...,...,...,...,...,...,...
12563,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U843,Resistencia a drogas antituberculosas
12564,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U847,Resistencia a múltiples drogas antimicrobianas
12565,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U848,Resistencia a otras drogas antimicrobianas esp...
12566,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U849,Resistencia a drogas antimicrobianas no especi...
12567,22,Códigos para propósitos especiales (U00-U99),U85,Resistencia a drogas antineoplásicas,U85X,Resistencia a drogas antineoplásicas

## Anexo 3: división administrativa Colombia

In [3]:
data_divi = pd.read_excel("data/divipola.xlsx")
data_divi

,COD_DANE,COD_DEPARTAMENTO,DEPARTAMENTO,COD_MUNICIPIO,MUNICIPIO,FECHA1erFIS
0,91001,91,AMAZONAS,1,LETICIA,2020-03-31
1,91405,91,AMAZONAS,405,LA CHORRERA,2020-06-15
2,91407,91,AMAZONAS,407,LA PEDRERA,2020-07-17
3,91540,91,AMAZONAS,540,PUERTO NARIÑO,2020-04-15
4,91669,91,AMAZONAS,669,PUERTO SANTANDER,2020-06-24
...,...,...,...,...,...,...
1118,25438,25,CUNDINAMARCA,438,MEDINA,2025-01-01
1119,19022,19,CAUCA,22,ALMAGUER,2025-01-01
1120,19693,19,CAUCA,693,SAN SEBASTIÁN,2025-01-01
1121,73686,73,TOLIMA,686,SANTA ISABEL,2025-01-01
1122,99624,99,VICHADA,624,SANTA ROSALÍA,2025-01-01

# Descriptiva (CAPA BRONCE)

## Resumen de Variables

In [4]:
## Función de resumen de variables

import pandas as pd
import numpy as np
def resumen_variables(df):
    """
    Genera una tabla resumen de las variables de un DataFrame.    
    Parámetros:    -----------
    df : pandas.DataFrame    
    Retorna:    --------
    resumen_df : pandas.DataFrame
    """    
    resumen = []
    for col in df.columns:
        tipo = df[col].dtype        
        # Clasificación general del tipo de variable
        if pd.api.types.is_numeric_dtype(df[col]):
            categoria = "Numérica"
        elif pd.api.types.is_datetime64_any_dtype(df[col]):
            categoria = "Fecha"
        elif pd.api.types.is_bool_dtype(df[col]):
            categoria = "Booleana"
        else:
            categoria = "Categórica/Texto"        
        # Cantidad de valores únicos
        valores_unicos = df[col].nunique(dropna=True)        
        # Porcentaje de nulos
        porcentaje_nulos = round(df[col].isnull().mean() * 100, 2)        
        # Ejemplo de valores
        ejemplo_valores = df[col].dropna().unique()[:5]
        ejemplo_valores = ", ".join(map(str, ejemplo_valores))        
        resumen.append({
            "Variable": col,
            "Tipo_Dato": str(tipo),
            "Categoria": categoria,
            "Valores_Unicos": valores_unicos,
            "Nulos_%": porcentaje_nulos,
            "Ejemplo_Valores": ejemplo_valores
        })
    resumen_df = pd.DataFrame(resumen)
    return resumen_df

In [5]:
resumen_variables(data_anex_1)

,Variable,Tipo_Dato,Categoria,Valores_Unicos,Nulos_%,Ejemplo_Valores
0,COD_DANE,int64,Numérica,1110,0.0,"66682, 17001, 25843, 23001, 73001"
1,COD_DEPARTAMENTO,int64,Numérica,33,0.0,"66, 17, 25, 23, 73"
2,COD_MUNICIPIO,int64,Numérica,576,0.0,"682, 1, 843, 175, 335"
3,AREA_DEFUNCION,int64,Numérica,4,0.0,"1, 3, 2, 9"
4,SITIO_DEFUNCION,int64,Numérica,7,0.0,"5, 1, 3, 4, 9"
5,AÑO,int64,Numérica,1,0.0,2019
6,MES,int64,Numérica,12,0.0,"11, 12, 9, 8, 7"
7,HORA,int64,Numérica,24,0.0,"23, 21, 20, 14, 8"
8,MINUTOS,int64,Numérica,60,0.0,"0, 10, 15, 20, 40"
9,SEXO,int64,Numérica,3,0.0,"2, 1, 3"
10,ESTADO_CIVIL,float64,Numérica,7,0.0,"5.0, 6.0, 4.0, 1.0, 9.0"
11,GRUPO_EDAD1,int64,Numérica,30,0.0,"15, 16, 19, 23, 20"
12,NIVEL_EDUCATIVO,int64,Numérica,14,0.0,"3, 2, 4, 99, 1"
13,MANERA_MUERTE,object,Categórica/Texto,6,0.0,"Homicidio, Natural, Sin Determinar, Suicidio, ..."
14,COD_MUERTE,object,Categórica/Texto,3271,0.0,"X994, C712, Y349, I678, F03"
15,IDPROFESIONAL,int64,Numérica,6,0.0,"1, 6, 3, 4, 2"

In [6]:
resumen_variables(data_anex_2)

,Variable,Tipo_Dato,Categoria,Valores_Unicos,Nulos_%,Ejemplo_Valores
0,Capítulo,int64,Numérica,22,0.0,"1, 2, 3, 4, 5"
1,Nombre capítulo,object,Categórica/Texto,22,0.0,Ciertas enfermedades infecciosas y parasitaria...
2,Código de la CIE-10 tres caracteres,object,Categórica/Texto,2053,0.0,"A00, A01, A02, A03, A04"
3,Descripción de códigos mortalidad a tres cara...,object,Categórica/Texto,2055,0.0,"Colera, Fiebres Tifoidea Y Paratifoidea, Otras..."
4,Código de la CIE-10 cuatro caracteres,object,Categórica/Texto,12568,0.0,"A000, A001, A009, A010, A011"
5,Descripcion de códigos mortalidad a cuatro ca...,object,Categórica/Texto,12566,0.0,"Colera debido a Vibrio cholerae 01, biotipo ch..."

In [7]:
resumen_variables(data_divi)

,Variable,Tipo_Dato,Categoria,Valores_Unicos,Nulos_%,Ejemplo_Valores
0,COD_DANE,int64,Numérica,1123,0.0,"91001, 91405, 91407, 91540, 91669"
1,COD_DEPARTAMENTO,int64,Numérica,33,0.0,"91, 5, 13, 47, 66"
2,DEPARTAMENTO,object,Categórica/Texto,33,0.0,"AMAZONAS, ANTIOQUIA, BOLÍVAR, MAGDALENA, RISAR..."
3,COD_MUNICIPIO,int64,Numérica,582,0.0,"1, 405, 407, 540, 669"
4,MUNICIPIO,object,Categórica/Texto,1038,0.0,"LETICIA, LA CHORRERA, LA PEDRERA, PUERTO NARIÑ..."
5,FECHA1erFIS,datetime64[ns],Fecha,188,0.0,"2020-03-31 00:00:00, 2020-06-15 00:00:00, 2020..."

# Tratamiento de datos (CAPA PLATA)

## Normalización de columnas

### Anexo 1

In [37]:
data_anex_1_pla = data_anex_1.copy()

## Normalización de nombres de columnas
data_anex_1_pla.columns = data_anex_1.columns.str.lower()
data_anex_1_pla

## renombre de columnas
data_anex_1_pla.rename(columns={
    "año": "anio",
    "grupo_edad1": "grupo_edad_1",
    "idprofesional": "id_profesional"
}, inplace=True)

data_anex_1_pla

,cod_dane,cod_departamento,cod_municipio,area_defuncion,sitio_defuncion,anio,mes,hora,minutos,sexo,estado_civil,grupo_edad_1,nivel_educativo,manera_muerte,cod_muerte,id_profesional
0,66682,66,682,1,5,2019,11,23,0,2,5.0,15,3,Homicidio,X994,1
1,17001,17,1,1,1,2019,12,21,10,1,6.0,16,2,Natural,C712,1
2,25843,25,843,1,1,2019,12,20,15,2,4.0,19,2,Sin Determinar,Y349,1
3,23001,23,1,1,1,2019,12,14,20,2,1.0,23,2,Natural,I678,1
4,73001,73,1,1,1,2019,11,8,40,2,4.0,23,2,Natural,F03,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,11,1,1,1,2019,5,0,0,1,5.0,13,3,Homicidio,X954,1
244351,97161,97,161,3,3,2019,9,4,30,1,1.0,17,2,Accidente,W330,3
244352,76001,76,1,1,5,2019,9,0,0,1,9.0,14,2,Homicidio,X954,1
244353,76109,76,109,1,1,2019,7,14,15,1,5.0,11,4,Accidente,W858,1
244354,76109,76,109,1,5,2019,2,0,0,1,1.0,11,2,Accidente,V892,1

### Anexo 2

In [38]:
import unicodedata

data_anex_2_pla = data_anex_2.copy()

## Normalización de nombres de columnas
data_anex_2_pla.columns = data_anex_2.columns.str.lower()

## Eliminación de signos de puntuación
data_anex_2_pla.columns = [
    unicodedata.normalize('NFKD', col).encode('ascii', errors='ignore').decode('utf-8')
    for col in data_anex_2_pla.columns
]

## Linea al piso para espacios
data_anex_2_pla.columns = data_anex_2_pla.columns.str.replace(' ', '_') 
data_anex_2_pla

## Reemplazo de nombres
data_anex_2_pla.rename(columns={
    "codigo_de_la_cie-10_tres_caracteres": "codigo_cie10_tres_caracteres",
    "descripcion__de_codigos_mortalidad_a_tres_caracteres": "descripcion_codigo_mortalidad_tres_caracteres",
    "codigo_de_la_cie-10_cuatro_caracteres": "cod_muerte",
    "descripcion__de_codigos_mortalidad_a_cuatro_caracteres": "descripcion_codigo_mortalidad_cuatro_caracteres",
}, inplace=True)

data_anex_2_pla

,capitulo,nombre_capitulo,codigo_cie10_tres_caracteres,descripcion_codigo_mortalidad_tres_caracteres,cod_muerte,descripcion_codigo_mortalidad_cuatro_caracteres
0,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A000,"Colera debido a Vibrio cholerae 01, biotipo ch..."
1,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A001,"Colera debido a Vibrio cholerae 01, biotipo el..."
2,1,Ciertas enfermedades infecciosas y parasitaria...,A00,Colera,A009,"Colera, no especificado"
3,1,Ciertas enfermedades infecciosas y parasitaria...,A01,Fiebres Tifoidea Y Paratifoidea,A010,Fiebre tifoidea
4,1,Ciertas enfermedades infecciosas y parasitaria...,A01,Fiebres Tifoidea Y Paratifoidea,A011,Fiebre paratifoidea A
...,...,...,...,...,...,...
12563,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U843,Resistencia a drogas antituberculosas
12564,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U847,Resistencia a múltiples drogas antimicrobianas
12565,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U848,Resistencia a otras drogas antimicrobianas esp...
12566,22,Códigos para propósitos especiales (U00-U99),U84,Resistencia a otras drogas antimicrobianas,U849,Resistencia a drogas antimicrobianas no especi...
12567,22,Códigos para propósitos especiales (U00-U99),U85,Resistencia a drogas antineoplásicas,U85X,Resistencia a drogas antineoplásicas

### Anexo 3

In [39]:
data_divi_pla = data_divi.copy()

data_divi_pla.columns = data_divi.columns.str.lower()

data_divi_pla

,cod_dane,cod_departamento,departamento,cod_municipio,municipio,fecha1erfis
0,91001,91,AMAZONAS,1,LETICIA,2020-03-31
1,91405,91,AMAZONAS,405,LA CHORRERA,2020-06-15
2,91407,91,AMAZONAS,407,LA PEDRERA,2020-07-17
3,91540,91,AMAZONAS,540,PUERTO NARIÑO,2020-04-15
4,91669,91,AMAZONAS,669,PUERTO SANTANDER,2020-06-24
...,...,...,...,...,...,...
1118,25438,25,CUNDINAMARCA,438,MEDINA,2025-01-01
1119,19022,19,CAUCA,22,ALMAGUER,2025-01-01
1120,19693,19,CAUCA,693,SAN SEBASTIÁN,2025-01-01
1121,73686,73,TOLIMA,686,SANTA ISABEL,2025-01-01
1122,99624,99,VICHADA,624,SANTA ROSALÍA,2025-01-01

## Remplazo de Categorias

### Anexo 1

In [40]:
from modulo_data.diccionarios import (
    dicc_area_defuncion,
    dicc_estado_civil,
    dicc_sexo,
    dicc_grupo_edad,
    dicc_meses,
    dicc_nivel_educativo,
    dicc_sitio_defuncion
)

# Diccionario maestro: columna -> diccionario de reemplazo
diccionarios = {
    'area_defuncion': dicc_area_defuncion,
    'estado_civil': dicc_estado_civil,
    'sexo': dicc_sexo,
    'grupo_edad_1': dicc_grupo_edad,
    'mes': dicc_meses,
    'nivel_educativo': dicc_nivel_educativo,
    'sitio_defuncion': dicc_sitio_defuncion
}

# Aplicación
for columna, diccionario in diccionarios.items():
    
    data_anex_1_pla[columna] = (
        data_anex_1_pla[columna]
        .map(diccionario)
        .fillna(data_anex_1_pla[columna])
    )

## Codigos muerte incompletos
data_anex_1_pla['cod_muerte'] = data_anex_1_pla['cod_muerte'].astype(str)
data_anex_1_pla['cod_muerte'] = data_anex_1_pla['cod_muerte'].apply(
    lambda x: x + 'X' if len(x) == 3 else x
)

data_anex_1_pla

C:\Users\User\AppData\Local\Temp\ipykernel_7684\1725687812.py:28: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(data_anex_1_pla[columna])

,cod_dane,cod_departamento,cod_municipio,area_defuncion,sitio_defuncion,anio,mes,hora,minutos,sexo,estado_civil,grupo_edad_1,nivel_educativo,manera_muerte,cod_muerte,id_profesional
0,66682,66,682,Cabecera municipal,Via pública,2019,Noviembre,23,0,Femenino,Estaba soltero(a),15,Básica secundaria,Homicidio,X994,1
1,17001,17,1,Cabecera municipal,Hospital/clínica,2019,Diciembre,21,10,Masculino,Estaba casado(a),16,Básica primaria,Natural,C712,1
2,25843,25,843,Cabecera municipal,Hospital/clínica,2019,Diciembre,20,15,Femenino,Estaba viudo(a),19,Básica primaria,Sin Determinar,Y349,1
3,23001,23,1,Cabecera municipal,Hospital/clínica,2019,Diciembre,14,20,Femenino,No estaba casado(a) y llevaba dos o más años v...,23,Básica primaria,Natural,I678,1
4,73001,73,1,Cabecera municipal,Hospital/clínica,2019,Noviembre,8,40,Femenino,Estaba viudo(a),23,Básica primaria,Natural,F03X,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,11,1,Cabecera municipal,Hospital/clínica,2019,Mayo,0,0,Masculino,Estaba soltero(a),13,Básica secundaria,Homicidio,X954,1
244351,97161,97,161,Rural disperso,Casa/domicilio,2019,Septiembre,4,30,Masculino,No estaba casado(a) y llevaba dos o más años v...,17,Básica primaria,Accidente,W330,3
244352,76001,76,1,Cabecera municipal,Via pública,2019,Septiembre,0,0,Masculino,Sin información,14,Básica primaria,Homicidio,X954,1
244353,76109,76,109,Cabecera municipal,Hospital/clínica,2019,Julio,14,15,Masculino,Estaba soltero(a),11,Media académica o clásica,Accidente,W858,1
244354,76109,76,109,Cabecera municipal,Via pública,2019,Febrero,0,0,Masculino,No estaba casado(a) y llevaba dos o más años v...,11,Básica primaria,Accidente,V892,1

# Eliminación de Columnas

## Anexo 1

In [41]:
data_anex_1_pla = data_anex_1_pla.drop(columns = ['cod_departamento', 'cod_municipio'])
data_anex_1_pla

,cod_dane,area_defuncion,sitio_defuncion,anio,mes,hora,minutos,sexo,estado_civil,grupo_edad_1,nivel_educativo,manera_muerte,cod_muerte,id_profesional
0,66682,Cabecera municipal,Via pública,2019,Noviembre,23,0,Femenino,Estaba soltero(a),15,Básica secundaria,Homicidio,X994,1
1,17001,Cabecera municipal,Hospital/clínica,2019,Diciembre,21,10,Masculino,Estaba casado(a),16,Básica primaria,Natural,C712,1
2,25843,Cabecera municipal,Hospital/clínica,2019,Diciembre,20,15,Femenino,Estaba viudo(a),19,Básica primaria,Sin Determinar,Y349,1
3,23001,Cabecera municipal,Hospital/clínica,2019,Diciembre,14,20,Femenino,No estaba casado(a) y llevaba dos o más años v...,23,Básica primaria,Natural,I678,1
4,73001,Cabecera municipal,Hospital/clínica,2019,Noviembre,8,40,Femenino,Estaba viudo(a),23,Básica primaria,Natural,F03X,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,Cabecera municipal,Hospital/clínica,2019,Mayo,0,0,Masculino,Estaba soltero(a),13,Básica secundaria,Homicidio,X954,1
244351,97161,Rural disperso,Casa/domicilio,2019,Septiembre,4,30,Masculino,No estaba casado(a) y llevaba dos o más años v...,17,Básica primaria,Accidente,W330,3
244352,76001,Cabecera municipal,Via pública,2019,Septiembre,0,0,Masculino,Sin información,14,Básica primaria,Homicidio,X954,1
244353,76109,Cabecera municipal,Hospital/clínica,2019,Julio,14,15,Masculino,Estaba soltero(a),11,Media académica o clásica,Accidente,W858,1
244354,76109,Cabecera municipal,Via pública,2019,Febrero,0,0,Masculino,No estaba casado(a) y llevaba dos o más años v...,11,Básica primaria,Accidente,V892,1

# Unión de Fuentes (CAPA ORO)

## Anexo 1 + Anexo 2 = Pre_fin

In [42]:
pre_fin = data_anex_1_pla.merge(data_anex_2_pla, on="cod_muerte", how="left")
pre_fin

,cod_dane,area_defuncion,sitio_defuncion,anio,mes,hora,minutos,sexo,estado_civil,grupo_edad_1,nivel_educativo,manera_muerte,cod_muerte,id_profesional,capitulo,nombre_capitulo,codigo_cie10_tres_caracteres,descripcion_codigo_mortalidad_tres_caracteres,descripcion_codigo_mortalidad_cuatro_caracteres
0,66682,Cabecera municipal,Via pública,2019,Noviembre,23,0,Femenino,Estaba soltero(a),15,Básica secundaria,Homicidio,X994,1,20,Causas externas de morbilidad y de mortalidad ...,X99,Agresion Con Objeto Cortante,"Agresion con objeto cortante, calles y carreteras"
1,17001,Cabecera municipal,Hospital/clínica,2019,Diciembre,21,10,Masculino,Estaba casado(a),16,Básica primaria,Natural,C712,1,2,Tumores [neoplasias] (C00-D48),C71,Tumor Maligno Del Encefalo,Tumor maligno del lobulo temporal
2,25843,Cabecera municipal,Hospital/clínica,2019,Diciembre,20,15,Femenino,Estaba viudo(a),19,Básica primaria,Sin Determinar,Y349,1,20,Causas externas de morbilidad y de mortalidad ...,Y34,Evento No Especificado De Intencion No Determi...,"Evento no especificado, de intencion no determ..."
3,23001,Cabecera municipal,Hospital/clínica,2019,Diciembre,14,20,Femenino,No estaba casado(a) y llevaba dos o más años v...,23,Básica primaria,Natural,I678,1,9,Enfermedades del sistema circulatorio (I00-I99),I67,Otras Enfermedades Cerebrovasculares,Otras enfermedades cerebrovasculares especific...
4,73001,Cabecera municipal,Hospital/clínica,2019,Noviembre,8,40,Femenino,Estaba viudo(a),23,Básica primaria,Natural,F03X,1,5,Trastornos mentales y del comportamiento (F00-...,F03,Demencia No Especificada,"Demencia , no especificada"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,Cabecera municipal,Hospital/clínica,2019,Mayo,0,0,Masculino,Estaba soltero(a),13,Básica secundaria,Homicidio,X954,1,20,Causas externas de morbilidad y de mortalidad ...,X95,"Agresion Con Disparo De Otras Armas Fuego, Y L...","Agresion con disparo de otras armas de fuego, ..."
244351,97161,Rural disperso,Casa/domicilio,2019,Septiembre,4,30,Masculino,No estaba casado(a) y llevaba dos o más años v...,17,Básica primaria,Accidente,W330,3,20,Causas externas de morbilidad y de mortalidad ...,W33,"Disparo De Rifle, Escopeta Y Arma Larga","Disparo de rifle, escopeta y arma larga, vivienda"
244352,76001,Cabecera municipal,Via pública,2019,Septiembre,0,0,Masculino,Sin información,14,Básica primaria,Homicidio,X954,1,20,Causas externas de morbilidad y de mortalidad ...,X95,"Agresion Con Disparo De Otras Armas Fuego, Y L...","Agresion con disparo de otras armas de fuego, ..."
244353,76109,Cabecera municipal,Hospital/clínica,2019,Julio,14,15,Masculino,Estaba soltero(a),11,Media académica o clásica,Accidente,W858,1,20,Causas externas de morbilidad y de mortalidad ...,W85,Exposicion A Lineas De Transmision Electrica,"Exposicion a lineas de transmision electrica, ..."
244354,76109,Cabecera municipal,Via pública,2019,Febrero,0,0,Masculino,No estaba casado(a) y llevaba dos o más años v...,11,Básica primaria,Accidente,V892,1,20,Causas externas de morbilidad y de mortalidad ...,V89,"Accidente De Vehículo De Motor O Sin Motor, Ti...","Persona lesionada en accidente de transito, de..."

In [43]:
resumen_variables(pre_fin)

,Variable,Tipo_Dato,Categoria,Valores_Unicos,Nulos_%,Ejemplo_Valores
0,cod_dane,int64,Numérica,1110,0.0,"66682, 17001, 25843, 23001, 73001"
1,area_defuncion,object,Categórica/Texto,4,0.0,"Cabecera municipal, Rural disperso, Centro pob..."
2,sitio_defuncion,object,Categórica/Texto,7,0.0,"Via pública, Hospital/clínica, Casa/domicilio,..."
3,anio,int64,Numérica,1,0.0,2019
4,mes,object,Categórica/Texto,12,0.0,"Noviembre, Diciembre, Septiembre, Agosto, Julio"
5,hora,int64,Numérica,24,0.0,"23, 21, 20, 14, 8"
6,minutos,int64,Numérica,60,0.0,"0, 10, 15, 20, 40"
7,sexo,object,Categórica/Texto,3,0.0,"Femenino, Masculino, Indeterminado"
8,estado_civil,object,Categórica/Texto,7,0.0,"Estaba soltero(a), Estaba casado(a), Estaba vi..."
9,grupo_edad_1,int64,Numérica,30,0.0,"15, 16, 19, 23, 20"
10,nivel_educativo,object,Categórica/Texto,14,0.0,"Básica secundaria, Básica primaria, Media acad..."
11,manera_muerte,object,Categórica/Texto,6,0.0,"Homicidio, Natural, Sin Determinar, Suicidio, ..."
12,cod_muerte,object,Categórica/Texto,3271,0.0,"X994, C712, Y349, I678, F03X"
13,id_profesional,int64,Numérica,6,0.0,"1, 6, 3, 4, 2"
14,capitulo,int64,Numérica,19,0.0,"20, 2, 9, 5, 14"
15,nombre_capitulo,object,Categórica/Texto,19,0.0,Causas externas de morbilidad y de mortalidad ...
16,codigo_cie10_tres_caracteres,object,Categórica/Texto,1028,0.0,"X99, C71, Y34, I67, F03"
17,descripcion_codigo_mortalidad_tres_caracteres,object,Categórica/Texto,1028,0.0,"Agresion Con Objeto Cortante, Tumor Maligno De..."
18,descripcion_codigo_mortalidad_cuatro_caracteres,object,Categórica/Texto,3271,0.0,"Agresion con objeto cortante, calles y carrete..."

In [46]:
len(pre_fin)

244355

In [44]:
data_gold = pre_fin.merge(data_divi_pla, on = 'cod_dane', how='left')
data_gold

,cod_dane,area_defuncion,sitio_defuncion,anio,mes,hora,minutos,sexo,estado_civil,grupo_edad_1,...,capitulo,nombre_capitulo,codigo_cie10_tres_caracteres,descripcion_codigo_mortalidad_tres_caracteres,descripcion_codigo_mortalidad_cuatro_caracteres,cod_departamento,departamento,cod_municipio,municipio,fecha1erfis
0,66682,Cabecera municipal,Via pública,2019,Noviembre,23,0,Femenino,Estaba soltero(a),15,...,20,Causas externas de morbilidad y de mortalidad ...,X99,Agresion Con Objeto Cortante,"Agresion con objeto cortante, calles y carreteras",66,RISARALDA,682,SANTA ROSA DE CABAL,2020-03-21
1,17001,Cabecera municipal,Hospital/clínica,2019,Diciembre,21,10,Masculino,Estaba casado(a),16,...,2,Tumores [neoplasias] (C00-D48),C71,Tumor Maligno Del Encefalo,Tumor maligno del lobulo temporal,17,CALDAS,1,MANIZALES,2020-03-12
2,25843,Cabecera municipal,Hospital/clínica,2019,Diciembre,20,15,Femenino,Estaba viudo(a),19,...,20,Causas externas de morbilidad y de mortalidad ...,Y34,Evento No Especificado De Intencion No Determi...,"Evento no especificado, de intencion no determ...",25,CUNDINAMARCA,843,VILLA DE SAN DIEGO DE UBATÉ,2020-03-28
3,23001,Cabecera municipal,Hospital/clínica,2019,Diciembre,14,20,Femenino,No estaba casado(a) y llevaba dos o más años v...,23,...,9,Enfermedades del sistema circulatorio (I00-I99),I67,Otras Enfermedades Cerebrovasculares,Otras enfermedades cerebrovasculares especific...,23,CÓRDOBA,1,MONTERÍA,2020-03-15
4,73001,Cabecera municipal,Hospital/clínica,2019,Noviembre,8,40,Femenino,Estaba viudo(a),23,...,5,Trastornos mentales y del comportamiento (F00-...,F03,Demencia No Especificada,"Demencia , no especificada",73,TOLIMA,1,IBAGUÉ,2020-03-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244350,11001,Cabecera municipal,Hospital/clínica,2019,Mayo,0,0,Masculino,Estaba soltero(a),13,...,20,Causas externas de morbilidad y de mortalidad ...,X95,"Agresion Con Disparo De Otras Armas Fuego, Y L...","Agresion con disparo de otras armas de fuego, ...",11,"BOGOTÁ, D.C.",1,"BOGOTÁ, D.C.",2020-02-27
244351,97161,Rural disperso,Casa/domicilio,2019,Septiembre,4,30,Masculino,No estaba casado(a) y llevaba dos o más años v...,17,...,20,Causas externas de morbilidad y de mortalidad ...,W33,"Disparo De Rifle, Escopeta Y Arma Larga","Disparo de rifle, escopeta y arma larga, vivienda",97,VAUPÉS,161,CARURÚ,2020-08-27
244352,76001,Cabecera municipal,Via pública,2019,Septiembre,0,0,Masculino,Sin información,14,...,20,Causas externas de morbilidad y de mortalidad ...,X95,"Agresion Con Disparo De Otras Armas Fuego, Y L...","Agresion con disparo de otras armas de fuego, ...",76,VALLE DEL CAUCA,1,SANTIAGO DE CALI,2020-03-02
244353,76109,Cabecera municipal,Hospital/clínica,2019,Julio,14,15,Masculino,Estaba soltero(a),11,...,20,Causas externas de morbilidad y de mortalidad ...,W85,Exposicion A Lineas De Transmision Electrica,"Exposicion a lineas de transmision electrica, ...",76,VALLE DEL CAUCA,109,BUENAVENTURA,2020-03-23
244354,76109,Cabecera municipal,Via pública,2019,Febrero,0,0,Masculino,No estaba casado(a) y llevaba dos o más años v...,11,...,20,Causas externas de morbilidad y de mortalidad ...,V89,"Accidente De Vehículo De Motor O Sin Motor, Ti...","Persona lesionada en accidente de transito, de...",76,VALLE DEL CAUCA,109,BUENAVENTURA,2020-03-23

In [45]:
resumen_variables(data_gold)

,Variable,Tipo_Dato,Categoria,Valores_Unicos,Nulos_%,Ejemplo_Valores
0,cod_dane,int64,Numérica,1110,0.0,"66682, 17001, 25843, 23001, 73001"
1,area_defuncion,object,Categórica/Texto,4,0.0,"Cabecera municipal, Rural disperso, Centro pob..."
2,sitio_defuncion,object,Categórica/Texto,7,0.0,"Via pública, Hospital/clínica, Casa/domicilio,..."
3,anio,int64,Numérica,1,0.0,2019
4,mes,object,Categórica/Texto,12,0.0,"Noviembre, Diciembre, Septiembre, Agosto, Julio"
5,hora,int64,Numérica,24,0.0,"23, 21, 20, 14, 8"
6,minutos,int64,Numérica,60,0.0,"0, 10, 15, 20, 40"
7,sexo,object,Categórica/Texto,3,0.0,"Femenino, Masculino, Indeterminado"
8,estado_civil,object,Categórica/Texto,7,0.0,"Estaba soltero(a), Estaba casado(a), Estaba vi..."
9,grupo_edad_1,int64,Numérica,30,0.0,"15, 16, 19, 23, 20"
10,nivel_educativo,object,Categórica/Texto,14,0.0,"Básica secundaria, Básica primaria, Media acad..."
11,manera_muerte,object,Categórica/Texto,6,0.0,"Homicidio, Natural, Sin Determinar, Suicidio, ..."
12,cod_muerte,object,Categórica/Texto,3271,0.0,"X994, C712, Y349, I678, F03X"
13,id_profesional,int64,Numérica,6,0.0,"1, 6, 3, 4, 2"
14,capitulo,int64,Numérica,19,0.0,"20, 2, 9, 5, 14"
15,nombre_capitulo,object,Categórica/Texto,19,0.0,Causas externas de morbilidad y de mortalidad ...
16,codigo_cie10_tres_caracteres,object,Categórica/Texto,1028,0.0,"X99, C71, Y34, I67, F03"
17,descripcion_codigo_mortalidad_tres_caracteres,object,Categórica/Texto,1028,0.0,"Agresion Con Objeto Cortante, Tumor Maligno De..."
18,descripcion_codigo_mortalidad_cuatro_caracteres,object,Categórica/Texto,3271,0.0,"Agresion con objeto cortante, calles y carrete..."
19,cod_departamento,int64,Numérica,33,0.0,"66, 17, 25, 23, 73"
20,departamento,object,Categórica/Texto,33,0.0,"RISARALDA, CALDAS, CUNDINAMARCA, CÓRDOBA, TOLIMA"
21,cod_municipio,int64,Numérica,576,0.0,"682, 1, 843, 175, 335"
22,municipio,object,Categórica/Texto,1026,0.0,"SANTA ROSA DE CABAL, MANIZALES, VILLA DE SAN D..."
23,fecha1erfis,datetime64[ns],Fecha,188,0.0,"2020-03-21 00:00:00, 2020-03-12 00:00:00, 2020..."

In [47]:
len(pre_fin)

244355

# Funciones de Ejecución

## Para lectura

In [1]:
from modulo_data.lectura import cargar_archivos_excel
data = cargar_archivos_excel("data")

Todos los archivos fueron validados y cargados correctamente.

## Para tratamiento a capa Plata

In [2]:
from modulo_data.tratamiento_data import transformacion_data
data_gold = transformacion_data(data['anexo_1'], data['anexo_2'], data['anexo_3'])

g:\Mi unidad\Maestria\Maestria IA\2. Clases\2.4 Aplicaciones I\dash_mortalidad\dash_visual_la_salle_mortalidad\modulo_data\tratamiento_data.py:57: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(data_anex_1_pla[columna])

## Generación Capa Gold

In [3]:
from modulo_data.capa_gold import capa_gold
capa_gold_data = capa_gold(data_gold[0], data_gold[1], data_gold[2])

## Almacenamiento Fuente Final

In [4]:
from modulo_data.almacenamiento_gold import almacenar_gold
almacenar_gold(capa_gold_data, "data/parquet_gold")

Parquet particionado almacenado en: data/parquet_gold